services:
  redis:
    image: redis:latest
    container_name: redis_container
    environment:
      - REDIS_PASSWORD=password
      - REDIS_USER=balamut
      - REDIS_USER_PASSWORD=password
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    restart: unless-stopped
    networks:
      - echat-net
  postgresql:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: balamut
      POSTGRES_PASSWORD: maksym
      PGDATA: /data/postgres
      POSTGRES_DB: chat
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - echat-net
    restart: unless-stopped
  backend:
    container_name: backend
    image: xemii16/echat:0.1.5-SNAPSHOT
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
      - redis
    networks:
      - echat-net
networks:
  echat-net:
    driver: bridge
volumes:
  postgres:
  redis:
