services:
  postgresql:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: balamut
      POSTGRES_PASSWORD: maksym
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - echat-net
    restart: unless-stopped
  backend:
    container_name: backend
    image: xemii16/echat:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    networks:
      - echat-net
networks:
  echat-net:
    driver: bridge
volumes:
  postgres:
